HUDHealthcarePortal/Controllers/ManagementReport/ManagementReportController.cs
using System.Web.Mvc;
using BusinessService.Interfaces;
using HUDHealthcarePortal.BusinessService;

namespace HUDHealthcarePortal.Controllers.ManagementReport
{
    public class ManagementReportController : Controller
    {
        IManagementReportManager managementReportMgr;

        public ManagementReportController()
            : this(new ManagementReportManager())
        {

        }

        public ManagementReportController(IManagementReportManager managementReportManager)
        {
            managementReportMgr = managementReportManager;
        }

        //public ActionResult HighRiskProjectReport()
        //{
        //    ReportModel reportModel = managementReportMgr.GetHighRiskProjectReport(HudUserUtil.GetHudUserRole);

        //    return SelectViewBasedOnUserRole(reportModel);
        //}

       

        [HttpGet]
        public ActionResult DoNothing()
        {
            return new EmptyResult();
        }        
    }
}

HUDHealthcarePortal/Controllers/ManagementReport/MissingProjectReportController.cs
using System;
using System.Web;
using System.Web.Mvc;
using BusinessService.Interfaces;
using BusinessService.ManagementReport;
using Core;
using HUDHealthcarePortal.BusinessService;
using HUDHealthcarePortal.Core;
using HUDHealthcarePortal.Filters;
using HUDHealthcarePortal.Helpers;
using Model;
using MvcSiteMapProvider;
using MvcSiteMapProvider.Builder;

namespace HUDHealthcarePortal.Controllers.ManagementReport
{
    public class MissingProjectReportController : Controller
    {
        private IMissingProjectReportManager _missingProjectReportManager;

        public MissingProjectReportController()
            : this(new MissingProjectReportManager())
        {

        }

        public MissingProjectReportController(IMissingProjectReportManager missingProjectReportManager)
        {
            _missingProjectReportManager = missingProjectReportManager;
        }

        [HttpGet]
        //[AccessDeniedAuthorize(Roles = "Administrator,HUDAdmin,SuperUser,HUDDirector,WorkflowManager,AccountExecutive")]
        [AccessDeniedAuthorize(Roles = "Administrator,HUDAdmin,SuperUser")]
        public ActionResult Index()
        {
            var userName = UserPrincipal.Current.UserName;
            ReportModel reportModel;
            var year = DateTime.Now.Year;
            
            //var reportyear = EnumType.GetEnumFromDescription(year.ToString(), typeof (ReportYear));

            //var enumval = EnumType.EnumToValue(EnumType.Parse<ReportingPeriod>(reportyear.ToString()));
            ISiteMapNode parentNode = null;
            if (SiteMaps.Current.CurrentNode != null) parentNode = SiteMaps.Current.CurrentNode.ParentNode;
            var routeValues = SessionHelper.SessionGet<System.Web.Routing.RouteValueDictionary>(SessionHelper.SESSION_KEY_MISSING_PROJECT_LINK_DICT);
            if (parentNode != null && !parentNode.RouteValues.Keys.Contains("reportYear") && routeValues != null)
            {
                ReportYear yearVal = (ReportYear) routeValues["reportYear"];
                year = int.Parse(EnumType.GetEnumDescription(yearVal));
            }
            if (RoleManager.IsSuperUserRole(userName))
            {
                ViewBag.ExcelExportAction = "ExportMissingProjectSuperUser";
                ViewBag.PrintAction = "PrintMissingProjectSuperUser";
                ViewBag.ExcelActionParam = new {year};
                reportModel = _missingProjectReportManager.GetMissingProjectReport(HUDRole.SuperUser, userName, year);
                return View("~/Views/ManagementReport/MissingProject/SuperUserReport.cshtml", reportModel);
            }
            if (RoleManager.IsWorkloadManagerRole(userName))
            {
                ViewBag.ExcelExportAction = "ExportMissingProjectWLM";
                ViewBag.PrintAction = "PrintMissingProjectWLM";
                ViewBag.ExcelActionParam = new { year,userName };
                reportModel = _missingProjectReportManager.GetMissingProjectReport(HUDRole.WorkflowManager, userName, year);
                return View("~/Views/ManagementReport/MissingProject/WLMReport.cshtml", reportModel);
            }
            if (RoleManager.IsAccountExecutiveRole(userName))
            {
                ViewBag.ExcelExportAction = "ExportMissingProjectAE";
                ViewBag.PrintAction = "PrintMissingProjectAE";
                ViewBag.ExcelActionParam = new { year,userName };
                reportModel = _missingProjectReportManager.GetMissingProjectReport(HUDRole.AccountExecutive, userName, year);
                return View("~/Views/ManagementReport/MissingProject/AEReport.cshtml", reportModel);
            }
            
            return new EmptyResult();
        }

        [HttpGet]
        //[AccessDeniedAuthorize(Roles = "Administrator,HUDAdmin,SuperUser,HUDDirector,WorkflowManager,AccountExecutive")]
        [AccessDeniedAuthorize(Roles = "Administrator,HUDAdmin,SuperUser")]
        public ActionResult GetSuperUserMissingProjectForYear(int year)
        {
            ViewBag.ExcelExportAction = "ExportMissingProjectSuperUser";
            ViewBag.PrintAction = "PrintMissingProjectSuperUser";
            ViewBag.ExcelActionParam = new { year };
            var userName = UserPrincipal.Current.UserName;
            
            var reportModel = _missingProjectReportManager.GetMissingProjectReport(HUDRole.SuperUser, userName, year);
            return PartialView("~/Views/ManagementReport/MissingProject/_SuperUserReport.cshtml", reportModel);
        }

        [HttpGet]
        //[AccessDeniedAuthorize(Roles = "Administrator,HUDAdmin,SuperUser,HUDDirector")]
        [AccessDeniedAuthorize(Roles = "Administrator,HUDAdmin,SuperUser")]
        public ActionResult GetSuperUserWLMMissingProjectForYear(int year)
        {
            ViewBag.ExcelExportAction = "ExportMissingProjectSuperUserWLM";
            ViewBag.PrintAction = "PrintMissingProjectSuperUserWLM";
            ViewBag.ExcelActionParam = new { year };
            var userName = UserPrincipal.Current.UserName;
            
            var reportModel = _missingProjectReportManager.GetSuperUserMissingProjectReportWithWLM(userName, year);
            return PartialView("~/Views/ManagementReport/MissingProject/_SuperUserReport_WLM.cshtml", reportModel);
           
        }

        [HttpGet]
        //[AccessDeniedAuthorize(Roles = "Administrator,HUDAdmin,SuperUser,HUDDirector,WorkflowManager")]
        [AccessDeniedAuthorize(Roles = "Administrator,HUDAdmin,SuperUser")]
        public ActionResult GetWLMMissingProjectReportForYear(int year, string userName)
        {
            ViewBag.ExcelExportAction = "ExportMissingProjectWLM";
            ViewBag.PrintAction = "PrintMissingProjectWLM";
            ViewBag.ExcelActionParam = new { year, userName };
            var reportModel = _missingProjectReportManager.GetWorkloadManagerMissingProjectReport(userName, year);
            return PartialView("~/Views/ManagementReport/MissingProject/_WLMReport.cshtml", reportModel);
           
        }

        [HttpGet]
        //[AccessDeniedAuthorize(Roles = "Administrator,HUDAdmin,SuperUser,HUDDirector,WorkflowManager,AccountExecutive")]
        [AccessDeniedAuthorize(Roles = "Administrator,HUDAdmin,SuperUser")]
        public ActionResult GetAEMissingProjectReportForYear(int year, string userName)
        {
            ViewBag.ExcelExportAction = "ExportMissingProjectAE";
            ViewBag.PrintAction = "PrintMissingProjectAE";
            ViewBag.ExcelActionParam = new { year,userName };
            var reportModel = _missingProjectReportManager.GetAccountExecutiveMissingProjectReport(userName, year);
                return PartialView("~/Views/ManagementReport/MissingProject/_AEReport.cshtml", reportModel);
        }

       [HttpGet]
        //[AccessDeniedAuthorize(Roles = "Administrator,HUDAdmin,SuperUser,HUDDirector")]
        [AccessDeniedAuthorize(Roles = "Administrator,HUDAdmin,SuperUser")]
        [MvcSiteMapNode(Title = "Missing Project Report with WLM", PreservedRouteParameters = "reportYear", ParentKey = "MissingProjectReportId", Key = "SuperUserWLMMissingProjectReportId")]
        public ActionResult SuperUserWLMMissingProjectReportDetail(ReportYear reportYear)
       {
            ViewBag.ExcelExportAction = "ExportMissingProjectSuperUserWLM";
            ViewBag.PrintAction = "PrintMissingProjectSuperUserWLM";
            
            var year = EnumType.GetEnumDescription(reportYear);
            ViewBag.ExcelActionParam = new { year };
            var reportModel = _missingProjectReportManager.GetSuperUserMissingProjectReportWithWLM(UserPrincipal.Current.UserName,int.Parse(year));
            var routeValuesDict = new System.Web.Routing.RouteValueDictionary()
            {
                {"reportYear", reportYear}
            };
            Session[SessionHelper.SESSION_KEY_MISSING_PROJECT_LINK_DICT] = routeValuesDict;
            return View("~/Views/ManagementReport/MissingProject/SuperUserReport_WLM.cshtml", reportModel);

        }

        [HttpGet]
       //[AccessDeniedAuthorize(Roles = "Administrator,HUDAdmin,SuperUser,HUDDirector,WorkflowManager")]
        [AccessDeniedAuthorize(Roles = "Administrator,HUDAdmin,SuperUser")]
        [MvcSiteMapNode(Title = "WLM Missing Project Report", PreservedRouteParameters = "wlmId,reportYear", ParentKey = "SuperUserWLMMissingProjectReportId", Key = "WLMMissingProjectReportId")]
       public ActionResult WLMMissingProjectReportDetail(string wlmId, ReportYear reportYear)
        {
            ViewBag.ExcelExportAction = "ExportMissingProjectWLM";
            ViewBag.PrintAction = "PrintMissingProjectWLM";
            var year = EnumType.GetEnumDescription(reportYear);
            var userName = wlmId;
            ViewBag.ExcelActionParam = new { year,userName };
            ControllerHelper.PopulateParentNodeRouteValuesForMissingProject();
            var reportModel = _missingProjectReportManager.GetWorkloadManagerMissingProjectReport(wlmId,
                int.Parse(year));
            var routeValuesDict = new System.Web.Routing.RouteValueDictionary()
            {
                {"wlmId", wlmId},
                {"reportYear", reportYear}
            };
            Session[SessionHelper.SESSION_KEY_MISSING_PROJECT_LINK_DICT] = routeValuesDict;
            return View("~/Views/ManagementReport/MissingProject/WLMReport.cshtml", reportModel);
        }

        [HttpGet]
        //[AccessDeniedAuthorize(Roles = "Administrator,HUDAdmin,SuperUser,HUDDirector,WorkflowManager,AccountExecutive")]
        [AccessDeniedAuthorize(Roles = "Administrator,HUDAdmin,SuperUser")]
        [MvcSiteMapNode(Title = "AE Missing Project Report", PreservedRouteParameters = "aeId,reportYear", ParentKey = "WLMMissingProjectReportId", Key = "AEMissingProjectReportId")]
        public ActionResult AEMissingProjectReportDetail(string aeId, ReportYear reportYear)
        {
            return MissingProjectReportForAE(aeId, reportYear);

HUDHealthcarePortal/Views/ManagementReport/MissingProject/AEReport.cshtml
@using Core
@using Model
@model ReportModel
@{
    ViewBag.Title = "AEReport";
}

<script type="text/javascript">
    $(document).ready(function () {
        $("#yearList").change(function () {
            var url = '@Url.Action("GetAEMissingProjectReportForYear", "MissingProjectReport")';
            var selectedYear = $("#yearList").val();
            $("#year").val(selectedYear);
            $.ajax({
                url: url,
                data: { year: selectedYear, userName: $("#aeEmail").val() },
                contentType: "application/json; charset=utf-8",
                type: 'GET',
                cache: false,
                success: function (data) {
                    {
                        $("#dvAEReport").html('');
                        $("#dvAEReport").html(data);
                    }
                },
                error: function (XMLHttpRequest, textStatus, errorThrown) {
                    alert("Status: " + textStatus);
                    alert("Error: " + errorThrown);
                }
            });
            return false;

        });
    });

</script>

<div class="container-fluid">
    <div class="row">
        <div class="row" style="margin-left: 0px; margin-right: 0px;">
            <div class="container-fluid">
                <div class="row">
                    <span class="col-md-4 text-left">
                        @Html.Label("Report Name: ")
                    </span>
                    <span class="col-md-4">
                        @Html.DisplayName(EnumType.GetEnumDescription(Model.ReportHeaderModel.ReportType))
                    </span>
                </div>
            </div>

            <div class="container-fluid">
                <div class="row">
                    <span class="col-md-4 text-left">
                        @Html.Label("Report Generated as of: ")
                    </span>
                    <span class="col-md-4">
                        @DateTime.Today.AddDays(-1).ToShortDateString()
                    </span>
                </div>
            </div>

            <div class="container-fluid">
                <div class="row">
                    <span class="col-md-4 text-left">
                        @Html.Label("Select Report Year: ")
                    </span>
                    <span class="col-md-4">
                        @Html.EnumDropDownListFor(m => m.ReportHeaderModel.ReportYear, new { @id = "yearList" })
                        @Html.HiddenFor(m => m.ReportHeaderModel.ReportYear, new { @id = "year" })
                    </span>
                </div>
            </div>

            <div class="container-fluid">
                <div class="row">
                    <span class="col-md-4 text-left">
                        @Html.Label("Workload Manager: ")
                    </span>
                    <span class="col-md-4">
                        @Html.DisplayName(Model.ReportHeaderModel.HudWorkloadManagerName)

                    </span>
                </div>
            </div>

            <div class="container-fluid">
                <div class="row">
                    <span class="col-md-4 text-left">
                        @Html.Label("Account Executive: ")
                    </span>
                    <span class="col-md-4">
                        @Html.DisplayName(Model.ReportHeaderModel.HudProjectManagerName)
                        @Html.HiddenFor(m => m.ReportHeaderModel.HudProjectManagerEmailAddress, new { @id = "aeEmail" })
                    </span>
                </div>
            </div>
        </div>
    </div>

   
    <div class="row">
        <div id="dvAEReport" class="col-md-8">
            @Html.Partial("~/Views/ManagementReport/MissingProject/_AEReport.cshtml", Model)
        </div>
    </div>
</div>

HUDHealthcarePortal/Views/ManagementReport/MissingProject/SuperUserReport.cshtml
@using Core
@model Model.ReportModel
@{
    ViewBag.Title = "SuperUserMissingReportDetail";
}
<script type="text/javascript">
    $(document).ready(function () {
        $("#yearList").change(function () {
            var url = '@Url.Action("GetSuperUserMissingProjectForYear", "MissingProjectReport")';
            var selectedYear = $("#yearList").val();
            $("#year").val(selectedYear);
           $.ajax({
                url : url,
                data: { year: selectedYear },
                contentType: "application/json; charset=utf-8",
                type: 'GET',
                cache: false,
                success: function (data) {
                    {
                        $("#dvSuperUserReport").html('');
                        $("#dvSuperUserReport").html(data);
                    }
                },
                error: function (XMLHttpRequest, textStatus, errorThrown) {
                    alert("Status: " + textStatus);
                    alert("Error: " + errorThrown);
                }
            });
            return false;
           
        });
    });

</script>
<div class="container-fluid">
    <div class="row">
        <div class="row" style="margin-left: 0px; margin-right: 0px;">
            <div class="container-fluid">
                <div class="row">
                    <span class="col-md-4 text-left">
                        @Html.Label("Report Name: ")
                    </span>
                    <span class="col-md-4">
                        @Html.DisplayName(EnumType.GetEnumDescription(Model.ReportHeaderModel.ReportType))
                    </span>
                </div>
            </div>

            <div class="container-fluid">
                <div class="row">
                    <span class="col-md-4 text-left">
                        @Html.Label("Report Generated as of: ")
                    </span>
                    <span class="col-md-4">
                        @DateTime.Today.AddDays(-1).ToShortDateString()
                    </span>
                </div>
            </div>

            <div class="container-fluid">
                <div class="row">
                    <span class="col-md-4 text-left">
                        @Html.Label("Select Report Year: ")
                    </span>
                    <span class="col-md-4">
                        @Html.EnumDropDownListFor(m => m.ReportHeaderModel.ReportYear, new { @id = "yearList" })
                        @Html.HiddenFor(m => m.ReportHeaderModel.ReportYear, new { @id = "year" })
                    </span>
                </div>
            </div>
        </div>
    </div>

    
    <div class="row">
        <div id="dvSuperUserReport" class="col-md-8">
            @Html.Partial("~/Views/ManagementReport/MissingProject/_SuperUserReport.cshtml", Model)
        </div>
    </div>
    </div>

HUDHealthcarePortal/Views/ManagementReport/MissingProject/SuperUserReport_WLM.cshtml
@using Core
@using Model
@model Model.ReportModel
@{
    ViewBag.Title = "SuperUserMissingReportWLMDetail";
}

<script type="text/javascript">
    $(document).ready(function () {
        $("#yearList").change(function () {
            var url = '@Url.Action("GetSuperUserWLMMissingProjectForYear", "MissingProjectReport")';
            var selectedYear = $("#yearList").val();
            $("#year").val(selectedYear);
            $.ajax({
                url : url,
                data: { year: selectedYear },
                contentType: "application/json; charset=utf-8",
                type: 'GET',
                cache: false,
                success: function (data) {
                    {
                        $("#dvSuperUserWLMReport").html('');
                        $("#dvSuperUserWLMReport").html(data);
                    }
                },
                error: function (XMLHttpRequest, textStatus, errorThrown) {
                    alert("Status: " + textStatus);
                    alert("Error: " + errorThrown);
                }
            });
            return false;

        });
    });
</script>
    <div class="container-fluid">
        <div class="row">
            <div class="row" style="margin-left: 0px; margin-right: 0px;">
                <div class="container-fluid">
                    <div class="row">
                        <span class="col-md-4 text-left">
                            @Html.Label("Report Name: ")
                        </span>
                        <span class="col-md-4">
                            @Html.DisplayName(EnumType.GetEnumDescription(Model.ReportHeaderModel.ReportType))
                        </span>
                    </div>
                </div>

                <div class="container-fluid">
                    <div class="row">
                        <span class="col-md-4 text-left">
                            @Html.Label("Report Generated as of: ")
                        </span>
                        <span class="col-md-4">
                            @DateTime.Today.AddDays(-1).ToShortDateString()
                        </span>
                    </div>
                </div>

                <div class="container-fluid">
                    <div class="row">
                        <span class="col-md-4 text-left">
                            @Html.Label("Select Report Year: ")
                        </span>
                        <span class="col-md-4">
                            @Html.EnumDropDownListFor(m => m.ReportHeaderModel.ReportYear, new { @id = "yearList" })
                            @Html.HiddenFor(m => m.ReportHeaderModel.ReportYear, new { @id = "year" })
                        </span>
                    </div>
                </div>
            </div>
        </div>

        <div class="row">
            <div style="float:right;margin-right: 450px;">
                <div>
                    @if (Model.ReportGridModelList.Count > 0)
                {
                    @Html.ImageActionLink(UrlHelper.GenerateContentUrl(@"~/Images/icon_excelBg.jpg", Html.ViewContext.HttpContext), "Export to Excel", (string)ViewBag.ExcelExportAction, "ExcelExport", (object)ViewBag.ExcelActionParam, new { @class = "excelExport" }, null)
                }
                    @if (Model.ReportGridModelList.Count > 0 && Core.WebUiConstants.ShowPrintIcon)
                {
                    @Html.ImageActionLink(UrlHelper.GenerateContentUrl(@"~/Images/icon_print.jpg", Html.ViewContext.HttpContext), "Print", (string)ViewBag.PrintAction, "Print", (object)ViewBag.ExcelActionParam, new { target = "_blank" }, null)
                }
                </div>
            </div>
        </div>
        <div class="row">
            <div id="dvSuperUserWLMReport" class="col-md-8">
                @Html.Partial("~/Views/ManagementReport/MissingProject/_SuperUserReport_WLM.cshtml", Model)
            </div>
        </div>
    </div>

HUDHealthcarePortal/Views/ManagementReport/MissingProject/WLMReport.cshtml
@using Core
@using Model
@model Model.ReportModel
@{
    ViewBag.Title = "WLMMissingReportDetail";
}

<script type="text/javascript">
    $(document).ready(function () {
        $("#yearList").change(function () {
            var url = '@Url.Action("GetWLMMissingProjectReportForYear", "MissingProjectReport")';
            var selectedYear = $("#yearList").val();
            $("#year").val(selectedYear);
            $.ajax({
                url: url,
                data: { year: selectedYear, userName: $("#wlmEmail").val() },
                contentType: "application/json; charset=utf-8",
                type: 'GET',
                cache: false,
                success: function (data) {
                    {
                        $("#dvWLMReport").html('');
                        $("#dvWLMReport").html(data);
                    }
                },
                error: function (XMLHttpRequest, textStatus, errorThrown) {
                    alert("Status: " + textStatus);
                    alert("Error: " + errorThrown);
                }
            });
            return false;

        });
    });

</script>

<div class="container-fluid">
    <div class="row">
        <div class="row" style="margin-left: 0px; margin-right: 0px;">
            <div class="container-fluid">
                <div class="row">
                    <span class="col-md-4 text-left">
                        @Html.Label("Report Name: ")
                    </span>
                    <span class="col-md-4">
                        @Html.DisplayName(EnumType.GetEnumDescription(Model.ReportHeaderModel.ReportType))
                    </span>
                </div>
            </div>

            <div class="container-fluid">
                <div class="row">
                    <span class="col-md-4 text-left">
                        @Html.Label("Report Generated as of: ")
                    </span>
                    <span class="col-md-4">
                        @DateTime.Today.AddDays(-1).ToShortDateString()
                    </span>
                </div>
            </div>

            <div class="container-fluid">
                <div class="row">
                    <span class="col-md-4 text-left">
                        @Html.Label("Select Report Year: ")
                    </span>
                    <span class="col-md-4">
                        @Html.EnumDropDownListFor(m => m.ReportHeaderModel.ReportYear, new { @id = "yearList" })
                        @Html.HiddenFor(m => m.ReportHeaderModel.ReportYear, new { @id = "year" })
                    </span>
                </div>
            </div>

            <div class="container-fluid">
                <div class="row">
                    <span class="col-md-4 text-left">
                        @Html.Label("Workload Manager: ")
                    </span>
                    <span class="col-md-4">
                        @if (Model.ReportGridModelList.Count > 0)
                        {
                            @Html.DisplayName(Model.ReportHeaderModel.HudWorkloadManagerName)
                            @Html.HiddenFor(m => m.ReportHeaderModel.HudWorkloadManagerEmailAddress, new { @id = "wlmEmail" })
                        }
                    </span>
                </div>
            </div>
        </div>
    </div>

    
    <div class="row">
        <div id="dvWLMReport" class="col-md-8">
            @Html.Partial("~/Views/ManagementReport/MissingProject/_WLMReport.cshtml", Model)
        </div>
    </div>
</div>

HUDHealthcarePortal/Views/ManagementReport/MissingProject/_SuperUserReport.cshtml
@model Model.ReportModel
<script type="text/javascript">
            $(document).ready(
                function () {
                    styleGrid();
                }
            );

            function styleGrid() {
                $('.webGrid .color').each(function (index, element) { $(element).parent().css('background-color', $(element).html()); });
            }
</script>
@{
    var grid = new WebGrid(Model.ReportGridModelList, canPage: true, rowsPerPage: 10,
        selectionFieldName: "selectedRow",
        ajaxUpdateContainerId: "gridContent",
        ajaxUpdateCallback: "styleGrid");

}

<div class="row">
    <div style="float:right;">
        <div>
            @if (Model.ReportGridModelList.Count > 0)
            {
                @Html.ImageActionLink(UrlHelper.GenerateContentUrl(@"~/Images/icon_excelBg.jpg", Html.ViewContext.HttpContext), "Export to Excel", (string)ViewBag.ExcelExportAction, "ExcelExport", (object)ViewBag.ExcelActionParam, new { @class = "excelExport" }, null)
            }
            @if (Model.ReportGridModelList.Count > 0 && Core.WebUiConstants.ShowPrintIcon)
            {
                @Html.ImageActionLink(UrlHelper.GenerateContentUrl(@"~/Images/icon_print.jpg", Html.ViewContext.HttpContext), "Print", (string)ViewBag.PrintAction, "Print", (object)ViewBag.ExcelActionParam, new { target = "_blank" }, null)
            }
        </div>
    </div>
</div>

<div id="gridContent">
    @{
        var gridColumns = new List<WebGridColumn>();
        gridColumns.Add(grid.Column("NumberOfProjects", "Number of Projects", format: (item) => (object)item.NumberOfProjects != null ? Html.ActionLink(((object)item.NumberOfProjects).ToString(), "SuperUserWLMMissingProjectReportDetail", "MissingProjectReport", new { reportYear = Model.ReportHeaderModel.ReportYear }, null) : Html.Raw(string.Empty)));
        gridColumns.Add(grid.Column("ExpectedNumber", "Expected Number of Reports", (item) => item.ExpectedNumber));
        gridColumns.Add(grid.Column("ReceivedNumber", "Received Number of Reports", (item) => item.ReceivedNumber));
        gridColumns.Add(grid.Column("MissingNumber", "Missing Number of Reports", (item) => item.MissingNumber));
    }

    @grid.GetHtml(tableStyle: "webGrid",
                headerStyle: "header_row",
                rowStyle: "item_row",
                alternatingRowStyle: "item_alt_row",
                selectedRowStyle: "select",
                mode: WebGridPagerModes.All,
                firstText: "<< First",
                previousText: "< Prev",
                nextText: "Next >",
                lastText: "Last >>",

                columns: gridColumns.ToArray())

</div>

HUDHealthcarePortal/Views/ManagementReport/MissingProject/_SuperUserReport_WLM.cshtml
@model Model.ReportModel
<script type="text/javascript">
            $(document).ready(
                function () {
                    styleGrid();
                }
            );

            function styleGrid() {
                $('.webGrid .color').each(function (index, element) { $(element).parent().css('background-color', $(element).html()); });
            }
</script>
@{
    var grid = new WebGrid(Model.ReportGridModelList, canPage: true, rowsPerPage: 10,
        selectionFieldName: "selectedRow",
        ajaxUpdateContainerId: "gridContent",
        ajaxUpdateCallback: "styleGrid");

}
<div id="gridContent">
    @{
        var gridColumns = new List<WebGridColumn>();
        gridColumns.Add(grid.Column("HudWorkloadManagerName", "Workload Manager Name", format: (item) => (object)item.HudWorkloadManagerName != null ? Html.ActionLink(((object)item.HudWorkloadManagerName).ToString(), "WLMMissingProjectReportDetail", "MissingProjectReport", new { wlmId = item.HudWorkloadManagerEmailAddress, reportYear = Model.ReportHeaderModel.ReportYear }, null) : Html.Raw(string.Empty)));
        gridColumns.Add(grid.Column("NumberOfProjects", "Number of Projects", (item) => item.NumberOfProjects));
        gridColumns.Add(grid.Column("ExpectedNumber", "Expected Number of Reports", (item) => item.ExpectedNumber));
        gridColumns.Add(grid.Column("ReceivedNumber", "Received Number of Reports", (item) => item.ReceivedNumber));
        gridColumns.Add(grid.Column("MissingNumber", "Missing Number of Reports", (item) => item.MissingNumber));
    }

    @grid.GetHtml(tableStyle: "webGrid",
                headerStyle: "header_row",
                rowStyle: "item_row",
                alternatingRowStyle: "item_alt_row",
                selectedRowStyle: "select",
                mode: WebGridPagerModes.All,
                firstText: "<< First",
                previousText: "< Prev",
                nextText: "Next >",
                lastText: "Last >>",

                columns: gridColumns.ToArray())

</div>